# -*- coding: utf-8 -*-
from . import mixins
from . import fmes_shift
from . import fmes_capacity_matrix
from . import mrp_production
from . import fmes_production_plan
from . import fmes_backlog_snapshot
from . import fmes_import_batch
from . import fmes_production_entry
from . import fmes_manpower_log
from . import fmes_operator_allocation
from . import mrp_workcenter
from . import fmes_maintenance_checklist_line
from . import fmes_maintenance_checklist_result
from . import fmes_maintenance_schedule
from . import maintenance_equipment
from . import maintenance_request
from . import mrp_workcenter_productivity_loss
from . import mrp_workcenter_productivity
from . import fmes_alert_rule
from . import fmes_alert
from . import fmes_report_schedule
from . import fmes_support_ticket
from . import sale_order_line
from . import res_users
