# -*- coding: utf-8 -*-
"""Scheduled report delivery (Requirement 12, deliverable 4).

`services/report_service.py` already gives the wizard and the XLSX
controller one shared, uniform way to fetch and format a report's data.
This model is the third caller of that same `get_report_data` — a schedule
just decides WHEN a report is produced and WHO receives it; the report
itself is generated by exactly the same code path, so a scheduled email can
never disagree with what the same report would show if generated by hand
on demand.

Field names and the four seeded defaults follow docs/11-reporting-analytics.md
section 5 and assumption `A36` exactly.

A schedule failing to render or send raises an activity for the Plant
Manager rather than failing silently (docs/11 section 5): a report that
quietly stops arriving is a worse failure than one that errors loudly, the
same principle the Phase 9 backlog cron and the Phase 11 alert engine
already apply to their own failure paths.
"""

import io
import logging
from datetime import datetime, time, timedelta

from odoo import _, api, fields, models

from ..services.report_service import REPORT_TYPES

try:
    import xlsxwriter
except ImportError:  # pragma: no cover - xlsxwriter ships with Odoo
    xlsxwriter = None

_logger = logging.getLogger(__name__)

FREQUENCIES = [('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')]
DAYS_OF_WEEK = [
    ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'),
    ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday'),
]
FORMATS = [('pdf', 'PDF'), ('xlsx', 'XLSX'), ('both', 'Both')]
PERIOD_OFFSETS = [
    ('yesterday', 'Yesterday'),
    ('last_week', 'Last Week'),
    ('last_month', 'Last Month'),
]


class FmesReportSchedule(models.Model):
    _name = 'fmes.report.schedule'
    _description = 'Scheduled Report'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'name'

    name = fields.Char(required=True)
    report_type = fields.Selection(REPORT_TYPES, required=True, index=True)
    frequency = fields.Selection(FREQUENCIES, required=True, default='daily')
    run_time = fields.Float(
        string='Run Time', required=True, default=7.0,
        help="Hour of day the report is sent, 24h, e.g. 7.5 = 07:30.")
    day_of_week = fields.Selection(
        DAYS_OF_WEEK, default='0',
        help="Only used when frequency is Weekly.")
    day_of_month = fields.Integer(
        default=1,
        help="Only used when frequency is Monthly. 1-28, to stay valid "
             "in every month.")
    department_ids = fields.Many2many(
        'hr.department', string='Departments',
        help="Leave empty to include every department.")
    workcenter_ids = fields.Many2many(
        'mrp.workcenter', string='Machines',
        help="Leave empty to include every machine.")
    recipient_ids = fields.Many2many('res.partner', string='Recipients')
    format = fields.Selection(FORMATS, required=True, default='pdf')
    period_offset = fields.Selection(
        PERIOD_OFFSETS, required=True, default='yesterday',
        help="Which period the report covers, relative to when it runs.")
    active = fields.Boolean(default=True)
    last_run = fields.Datetime(readonly=True, copy=False)
    next_run = fields.Datetime(
        readonly=True, copy=False, index=True,
        default=lambda self: fields.Datetime.now())
    company_id = fields.Many2one(
        'res.company', required=True, default=lambda self: self.env.company)

    _sql_constraints = [
        ('fmes_report_schedule_day_of_month_range',
         'CHECK(day_of_month >= 1 AND day_of_month <= 28)',
         'Day of month must be between 1 and 28.'),
    ]

    # ------------------------------------------------------------------
    # Period / next-run computation
    # ------------------------------------------------------------------
    def _compute_period(self, as_of):
        """(date_from, date_to) for this schedule's `period_offset`,
        relative to `as_of` (the moment the schedule is actually run)."""
        self.ensure_one()
        today = as_of.date()
        if self.period_offset == 'yesterday':
            day = today - timedelta(days=1)
            return day, day
        if self.period_offset == 'last_week':
            this_monday = today - timedelta(days=today.weekday())
            last_monday = this_monday - timedelta(days=7)
            return last_monday, last_monday + timedelta(days=6)
        # last_month
        first_of_this_month = today.replace(day=1)
        last_of_last_month = first_of_this_month - timedelta(days=1)
        first_of_last_month = last_of_last_month.replace(day=1)
        return first_of_last_month, last_of_last_month

    def _compute_next_run(self, after):
        """The next Datetime this schedule is due, strictly after `after`."""
        self.ensure_one()
        hour = int(self.run_time)
        minute = int(round((self.run_time - hour) * 60))
        target_time = time(hour=hour % 24, minute=minute % 60)

        if self.frequency == 'daily':
            candidate = datetime.combine(after.date(), target_time)
            if candidate <= after:
                candidate += timedelta(days=1)
            return candidate

        if self.frequency == 'weekly':
            target_weekday = int(self.day_of_week or '0')
            candidate = datetime.combine(after.date(), target_time)
            days_ahead = (target_weekday - candidate.weekday()) % 7
            candidate += timedelta(days=days_ahead)
            if candidate <= after:
                candidate += timedelta(days=7)
            return candidate

        # monthly
        day = max(1, min(self.day_of_month or 1, 28))
        candidate = datetime.combine(
            after.date().replace(day=day), target_time)
        if candidate <= after:
            month = candidate.month + 1
            year = candidate.year + (1 if month > 12 else 0)
            month = month if month <= 12 else 1
            candidate = candidate.replace(year=year, month=month)
        return candidate

    # ------------------------------------------------------------------
    # Cron
    # ------------------------------------------------------------------
    @api.model
    def _cron_send_scheduled_reports(self):
        now = fields.Datetime.now()
        due = self.search([('active', '=', True), ('next_run', '<=', now)])
        for schedule in due:
            try:
                schedule._send_scheduled_report(now)
            except Exception as exc:  # noqa: BLE001 - one bad schedule
                # must never block the rest of the run.
                _logger.exception(
                    "Scheduled report %s failed to send", schedule.name)
                schedule._notify_failure(exc)
            schedule.write({
                'last_run': now,
                'next_run': schedule._compute_next_run(now),
            })

    def _send_scheduled_report(self, as_of):
        self.ensure_one()
        if not self.recipient_ids:
            # Nothing to fail at and nobody to fail silently on — a schedule
            # is legitimately seeded before its recipients are configured
            # (assumption in docs/15). Advancing next_run without sending
            # is a no-op, not an error.
            return

        date_from, date_to = self._compute_period(as_of)
        data = self.env['fmes.report.service'].get_report_data(
            self.report_type, date_from, date_to,
            department_ids=self.department_ids.ids or None,
            workcenter_ids=self.workcenter_ids.ids or None,
            company=self.company_id)

        attachments = []
        if self.format in ('pdf', 'both'):
            attachments.append(
                self._render_pdf_attachment(data, date_from, date_to))
        if self.format in ('xlsx', 'both'):
            attachments.append(self._render_xlsx_attachment(data))

        self.env['mail.mail'].sudo().create({
            'subject': _("[Furnishing MES] %(title)s — %(period)s",
                        title=data['title'], period=data['period_label']),
            'body_html': _(
                "<p>Attached: %(title)s for %(period)s.</p>",
                title=data['title'], period=data['period_label']),
            'recipient_ids': [(6, 0, self.recipient_ids.ids)],
            'attachment_ids': [(6, 0, [a.id for a in attachments])],
        }).send()

    def _render_pdf_attachment(self, data, date_from, date_to):
        # A wizard record is what the report template expects as `docs`;
        # it carries only `report_type` and the filter fields — the
        # template re-fetches `data` itself from those, the same call
        # this method already made above, so the PDF can never disagree
        # with the `data` dict already used for the XLSX or the summary.
        wizard = self.env['fmes.report.wizard'].create({
            'report_type': self.report_type,
            'date_from': date_from,
            'date_to': date_to,
            'department_ids': [(6, 0, self.department_ids.ids)],
            'workcenter_ids': [(6, 0, self.workcenter_ids.ids)],
            'format': 'pdf',
        })
        pdf_content, _report_type = self.env['ir.actions.report'].sudo(
            )._render_qweb_pdf(
                'furnishing_mes.action_report_fmes_generic', wizard.ids)
        return self.env['ir.attachment'].sudo().create({
            'name': '%s.pdf' % data['title'],
            'type': 'binary',
            'raw': pdf_content,
            'mimetype': 'application/pdf',
        })

    def _render_xlsx_attachment(self, data):
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True})
        self.env['fmes.report.service'].write_xlsx(workbook, data)
        workbook.close()
        return self.env['ir.attachment'].sudo().create({
            'name': '%s.xlsx' % data['title'],
            'type': 'binary',
            'raw': output.getvalue(),
            'mimetype': ('application/vnd.openxmlformats-officedocument'
                        '.spreadsheetml.sheet'),
        })

    def _notify_failure(self, exc):
        self.ensure_one()
        manager_group = self.env.ref('furnishing_mes.group_fmes_manager')
        managers = self.env['res.users'].search(
            [('groups_id', '=', manager_group.id)])
        for manager in managers:
            self.activity_schedule(
                'mail.mail_activity_data_todo',
                summary=_("Scheduled report failed: %s", self.name),
                note=_("%(name)s could not be generated or sent: %(error)s",
                      name=self.name, error=str(exc)),
                user_id=manager.id)

    def action_run_now(self):
        for schedule in self:
            schedule._send_scheduled_report(fields.Datetime.now())
        return True
