# -*- coding: utf-8 -*-
"""XLSX export of a released production plan.

Planners live in Excel and will keep sharing schedules that way for a while
after go-live. Exporting the plan they generated is what makes the move off
manual planning painless rather than a fight.
"""

import io

from odoo import _, http
from odoo.exceptions import AccessError, UserError
from odoo.http import content_disposition, request

try:
    import xlsxwriter
except ImportError:  # pragma: no cover - xlsxwriter ships with Odoo
    xlsxwriter = None


class FmesPlanExport(http.Controller):

    @http.route('/fmes/plan/<int:plan_id>/xlsx', type='http', auth='user')
    def export_plan_xlsx(self, plan_id, **kwargs):
        if xlsxwriter is None:
            raise UserError(_("xlsxwriter is not available on this server."))

        # Existence first: check_access on a deleted record raises MissingError,
        # which surfaces as a 400 rather than the 404 this should be.
        plan = request.env['fmes.production.plan'].browse(plan_id).exists()
        if not plan:
            raise request.not_found()
        # Then the user's own rights: the record rules decide whether this plan
        # is visible, not the URL. A plan the user may not read returns the same
        # 404 as one that does not exist, so the route never confirms that a
        # plan id is real to someone who has no business knowing.
        try:
            plan.check_access('read')
        except AccessError:
            raise request.not_found()

        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True,
                                                'default_date_format': 'yyyy-mm-dd'})
        self._write_summary(workbook, plan)
        self._write_lines(workbook, plan)
        self._write_by_machine(workbook, plan)
        workbook.close()

        content = output.getvalue()
        filename = '%s.xlsx' % (plan.name or 'production_plan').replace('/', '_')
        return request.make_response(content, headers=[
            ('Content-Type',
             'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'),
            ('Content-Length', len(content)),
            ('Content-Disposition', content_disposition(filename)),
        ])

    # ------------------------------------------------------------------
    # Sheets
    # ------------------------------------------------------------------
    def _formats(self, workbook):
        return {
            'title': workbook.add_format(
                {'bold': True, 'font_size': 14, 'font_color': '#0e2238'}),
            'header': workbook.add_format(
                {'bold': True, 'bg_color': '#0e2238', 'font_color': '#ffffff',
                 'border': 1, 'align': 'center', 'valign': 'vcenter',
                 'text_wrap': True}),
            'label': workbook.add_format({'bold': True}),
            'date': workbook.add_format({'num_format': 'yyyy-mm-dd'}),
            'qty': workbook.add_format({'num_format': '#,##0.00'}),
            'hours': workbook.add_format({'num_format': '#,##0.00'}),
            'pct': workbook.add_format({'num_format': '0.0"%"'}),
            'warn': workbook.add_format(
                {'num_format': '0.0"%"', 'bg_color': '#f8d7da',
                 'font_color': '#842029', 'bold': True}),
        }

    def _write_summary(self, workbook, plan):
        fmt = self._formats(workbook)
        sheet = workbook.add_worksheet('Summary')
        sheet.set_column(0, 0, 26)
        sheet.set_column(1, 1, 40)

        sheet.write(0, 0, 'Production Plan %s' % plan.name, fmt['title'])
        rows = [
            ('Plan Type', dict(plan._fields['plan_type'].selection).get(
                plan.plan_type, plan.plan_type)),
            ('Period', '%s to %s' % (plan.date_from, plan.date_to)),
            ('Status', dict(plan._fields['state'].selection).get(
                plan.state, plan.state)),
            ('Generated By', dict(plan._fields['generated_by'].selection).get(
                plan.generated_by, plan.generated_by)),
            ('Departments', ', '.join(
                plan.department_ids.mapped('name')) or 'All'),
            ('Company', plan.company_id.name),
            ('Plan Lines', plan.line_count),
            ('Planned Quantity', plan.total_planned_qty),
            ('Planned Hours', plan.total_planned_hours),
            ('Available Hours', plan.total_available_hours),
        ]
        row = 2
        for label, value in rows:
            sheet.write(row, 0, label, fmt['label'])
            sheet.write(row, 1, value)
            row += 1
        sheet.write(row, 0, 'Capacity Utilisation', fmt['label'])
        sheet.write(row, 1, plan.capacity_utilization_pct,
                    fmt['warn'] if plan.capacity_utilization_pct > 100
                    else fmt['pct'])
        row += 2

        if plan.unscheduled_demand_note:
            sheet.write(row, 0, 'Unscheduled Demand', fmt['label'])
            for line in plan.unscheduled_demand_note.split('\n'):
                sheet.write(row, 1, line)
                row += 1

    def _write_lines(self, workbook, plan):
        fmt = self._formats(workbook)
        sheet = workbook.add_worksheet('Plan Lines')
        headers = ['Date', 'Shift', 'Machine', 'Department', 'Product',
                   'Planned Qty', 'Rate/Hour', 'Hours', 'Changeover (min)',
                   'Manpower', 'Manufacturing Order', 'Work Order',
                   'Deadline', 'Source', 'Status']
        widths = [12, 10, 22, 18, 30, 12, 11, 10, 15, 10, 20, 20, 12, 14, 12]
        for col, (header, width) in enumerate(zip(headers, widths)):
            sheet.write(0, col, header, fmt['header'])
            sheet.set_column(col, col, width)
        sheet.freeze_panes(1, 0)
        sheet.autofilter(0, 0, max(len(plan.line_ids), 1), len(headers) - 1)

        selections = {
            'source': dict(
                plan.line_ids._fields['source'].selection),
            'state': dict(plan.line_ids._fields['state'].selection),
        }
        for row, line in enumerate(plan.line_ids, start=1):
            sheet.write_datetime(row, 0, line.date, fmt['date'])
            sheet.write(row, 1, line.shift_id.code or '')
            sheet.write(row, 2, line.workcenter_id.name or '')
            sheet.write(row, 3, line.department_id.name or '')
            sheet.write(row, 4, line.product_id.display_name or '')
            sheet.write_number(row, 5, line.planned_qty, fmt['qty'])
            sheet.write_number(row, 6, line.output_rate, fmt['qty'])
            sheet.write_number(row, 7, line.planned_hours, fmt['hours'])
            sheet.write_number(row, 8, line.changeover_minutes or 0)
            sheet.write_number(row, 9, line.planned_manpower or 0)
            sheet.write(row, 10, line.production_id.name or '')
            sheet.write(row, 11, line.workorder_id.name or '')
            if line.date_deadline:
                sheet.write_datetime(row, 12, line.date_deadline, fmt['date'])
            else:
                sheet.write(row, 12, '')
            sheet.write(row, 13, selections['source'].get(line.source, ''))
            sheet.write(row, 14, selections['state'].get(line.state, ''))

    def _write_by_machine(self, workbook, plan):
        """Machine-wise, shift-wise load — the view a planner checks first."""
        fmt = self._formats(workbook)
        sheet = workbook.add_worksheet('Load by Machine')
        headers = ['Machine', 'Date', 'Shift', 'Planned Hours',
                   'Available Hours', 'Utilisation %', 'Lines']
        widths = [24, 12, 10, 14, 16, 14, 8]
        for col, (header, width) in enumerate(zip(headers, widths)):
            sheet.write(0, col, header, fmt['header'])
            sheet.set_column(col, col, width)
        sheet.freeze_panes(1, 0)

        engine = plan.env['fmes.planning.engine']
        buckets = {}
        for line in plan.line_ids.filtered(lambda l: l.state != 'cancelled'):
            key = (line.workcenter_id, line.date, line.shift_id)
            entry = buckets.setdefault(key, {'hours': 0.0, 'count': 0})
            entry['hours'] += line.planned_hours
            entry['count'] += 1

        row = 1
        for (machine, date, shift), entry in sorted(
                buckets.items(),
                key=lambda item: (item[0][0].name or '', item[0][1],
                                  item[0][2].sequence)):
            capacity = engine._slot_capacity_hours(machine, shift, date)
            utilisation = (entry['hours'] / capacity * 100.0) if capacity else 0.0
            sheet.write(row, 0, machine.name or '')
            sheet.write_datetime(row, 1, date, fmt['date'])
            sheet.write(row, 2, shift.code or '')
            sheet.write_number(row, 3, entry['hours'], fmt['hours'])
            sheet.write_number(row, 4, capacity, fmt['hours'])
            sheet.write_number(row, 5, utilisation,
                               fmt['warn'] if utilisation > 100 else fmt['pct'])
            sheet.write_number(row, 6, entry['count'])
            row += 1
